In [60]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np
import sys
import os

from day_2 import get_data
from day_4 import get_columns, create_crossword
from day_10 import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [64]:
lines = get_data('data/example4-day-10.txt')[:-1]
columns = get_columns(lines)
char_per_line = len('89010132')
cw = create_crossword(columns, char_per_line)

cw_readable = cw.copy()
cw_readable

0  1  2  3  4  5  6  7
0  8  9  0  1  0  1  2  3
1  7  8  1  2  1  8  7  4
2  8  7  4  3  0  9  6  5
3  9  6  5  4  9  8  7  4
4  4  5  6  7  8  9  0  3
5  3  2  0  1  9  0  1  2
6  0  1  3  2  9  8  0  1
7  1  0  4  5  6  7  3  2

In [ ]:
cw = converting_to_integers(cw)
perms = get_all_permutations(cw)
# chemins_finaux = get_answer(cw, perms)
# answer = len(chemins_finaux)
# answer
answer_part1(perms)

In [705]:
chemin = {}
how_many_9 = len(how_many_for_specific_integer(9,cw))

possibilities = []

for j in range(len(perms[:])):
    coordinates = perms[j]
    for i in range(9):
        if comparing_two_coords_to_know_whether_consecutive_integers(coordinates[i], coordinates[i+1]):
            chemin[i] = ((coordinates[i]))
            chemin[i+1] = ((coordinates[i+1]))
    if len(chemin) < 9:
        print('length')

In [706]:
len(chemins_finaux)

64

In [697]:
perms

[{0: (0, 3),
  1: (1, 3),
  2: (2, 3),
  3: (3, 3),
  4: (3, 2),
  5: (3, 1),
  6: (3, 0),
  7: (4, 0),
  8: (5, 0),
  9: (6, 0)},
 {0: (0, 3),
  1: (1, 3),
  2: (2, 3),
  3: (3, 3),
  4: (3, 2),
  5: (3, 1),
  6: (3, 0),
  7: (4, 0),
  8: (5, 0),
  9: (6, 6)},
 {0: (0, 3),
  1: (1, 3),
  2: (2, 3),
  3: (3, 3),
  4: (3, 2),
  5: (3, 1),
  6: (3, 0),
  7: (4, 0),
  8: (5, 6),
  9: (6, 0)},
 {0: (0, 3),
  1: (1, 3),
  2: (2, 3),
  3: (3, 3),
  4: (3, 2),
  5: (3, 1),
  6: (3, 0),
  7: (4, 0),
  8: (5, 6),
  9: (6, 6)},
 {0: (0, 3),
  1: (1, 3),
  2: (2, 3),
  3: (3, 3),
  4: (3, 2),
  5: (3, 1),
  6: (3, 0),
  7: (4, 6),
  8: (5, 0),
  9: (6, 0)},
 {0: (0, 3),
  1: (1, 3),
  2: (2, 3),
  3: (3, 3),
  4: (3, 2),
  5: (3, 1),
  6: (3, 0),
  7: (4, 6),
  8: (5, 0),
  9: (6, 6)},
 {0: (0, 3),
  1: (1, 3),
  2: (2, 3),
  3: (3, 3),
  4: (3, 2),
  5: (3, 1),
  6: (3, 0),
  7: (4, 6),
  8: (5, 6),
  9: (6, 0)},
 {0: (0, 3),
  1: (1, 3),
  2: (2, 3),
  3: (3, 3),
  4: (3, 2),
  5: (3, 1),
  6: 

In [ ]:
chemin = {}
smallest_i = []

for i in range(9):
    if comparing_two_coords_to_know_whether_consecutive_integers(coordinates[i], coordinates[i+1]):
        chemin[i] = ((coordinates[i]))

    # elif len(coordinates[i+1]) > 1:
    #     if comparing_two_coords_to_know_whether_consecutive_integers(coordinates[i], coordinates[i+1][0]):
    #         chemin[i+1] = ((coordinates[i+1][0]))
    #     elif comparing_two_coords_to_know_whether_consecutive_integers(coordinates[i], coordinates[i+1][1]):
    #         chemin[i+1] = ((coordinates[i+1][1]))



    # elif len(coordinates[i]) < len(coordinates[i+1]):
    #     if len(coordinates[i]) == 1:
    #         for j in range(len(coordinates[i+1])):
    #             if comparing_two_coords_to_know_whether_consecutive_integers(coordinates[i], coordinates[i+1][j]):
    #                 chemin[i] = ((coordinates[i]))
    #                 chemin[i+1]= coordinates[i+1]
    #                 print(True)
    #     else:
    #         pass

    # elif len(coordinates[i]) == len(coordinates[i+1]):
    #     pass

    # elif len(coordinates[i]) > len(coordinates[i+1]):
    #     pass



# min = min(smallest_i)
# chemin.insert(min, coordinates[min])

0 1
1 2
2 3


In [581]:
chemin

{0: [(0, 3)],
 1: [(1, 3)],
 2: [(2, 3)],
 4: (3, 2),
 5: (3, 1),
 6: (3, 0),
 7: (4, 0),
 8: (5, 0),
 9: (6, 0)}

In [521]:
comparing_two_coords_to_know_whether_consecutive_integers(coordinates[6], coordinates[5])

True

In [526]:
abs(np.array(coordinates[6]) - np.array(coordinates[7]))

array([[1, 0],
       [1, 0]])

In [505]:
coordinate_7 = how_many_for_specific_integer(7,cw)
neigh_7, coordinate_7 = relevant_coordinates(7, cw)

coordinate_8 = how_many_for_specific_integer(8,cw)
neigh_8, coordinate_8 = relevant_coordinates(8, cw)

# coordinate_9 = how_many_for_specific_integer(9,cw)
# neigh_9, coordinate_9 = relevant_coordinates(9, cw)

In [ ]:
coordinate_7 = [coordinate_7[1]]
coordinate_8 = [coordinate_8[1]]

if comparing_two_coords_to_know_whether_consecutive_integers(coordinate_7, coordinate_8):


True

In [474]:
coordinate_7[0]

(4, 0)

In [ ]:
consecutives = [
    np.array([0,1]),
    np.array([1,0])
]



for i in consecutives:
    a, b = abs(np.array(coordinate_8) - np.array(coordinate_7))[0]
    print(a,b)
    if a == i[0] and b ==i[1]:
        return True

1 0
1 0
[(4, 0)]


In [327]:
cw_readable

0  1  2  3  4  5  6
0  .  .  .  0  .  .  .
1  .  .  .  1  .  .  .
2  .  .  .  2  .  .  .
3  6  5  4  3  4  5  6
4  7  .  .  .  .  .  7
5  8  .  .  .  .  .  8
6  9  .  .  .  .  .  9

In [ ]:
# Chemin for 1 zero

integer = 1

chemin_final = []

for i in range(len(relevant_0)):
    chemin = []
    for j in range(len(coord_1)):
        if (coord_1[j][0] == relevant_0[i][0][0]) and (coord_1[j][1] == relevant_0[i][0][1]):
            chemin.append(np.array(coordinates_0))
            chemin.append(coord_1[j])

    if chemin != []:
        chemin_final.append(chemin)

chemins = {}
for i in range(len(chemin_final)):
    chemins[f'chemin_{i}'] = chemin_final[i]
    # chemin_2 = chemin_final[1]
chemins

{'chemin_0': [array([[0, 3]]), array([0, 2])],
 'chemin_1': [array([[0, 3]]), array([1, 3])]}

In [ ]:
if len(chemin_final) == 1:
    neigh_1 = chemin[integer]
elif len(chemin_final) > 1:
    for i in range(len(chemin_final)):
        neigh_1 = chemin_final[i][integer]
        print(neigh_1)

[0 2]
[1 3]


In [340]:
neigh_1 = chemins['chemin_1'][integer]
neigh_1[0], neigh_1[1]

(1, 3)

In [342]:
neigh_1, len(neigh_1)

(array([1, 3]), 2)

In [345]:
neigh_0[0][0]

array([0, 2])

In [365]:
np.array(coordinates_0) , np.array(coord_1)

(array([[0, 3]]),
 array([[0, 2],
        [1, 3]]))

In [364]:
np.array(coordinates_0).shape , np.array(coord_1).shape

((1, 2), (2, 2))

In [ ]:
# // coordinates_for_specific_integer
integer=2

coord_2 = []
for k in range(len(neigh_1)):
    print(k)
    for i,j in neigh_1:
        print((i,j))
        # if cw.iloc[(i,j)]==integer:
        #     coord_2.append(np.array([i,j]))
coord_2

0


TypeError: cannot unpack non-iterable numpy.int64 object

In [ ]:
neigh_1 = chemin[integer]
coord_2 = coordinates_for_specific_integer(2, neigh_1)
coord_2

TypeError: 'numpy.int64' object is not iterable